services:
  db:
    image: "postgres"
    restart: "always"
    ports:
      - 5432:5432
    hostname: db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: sh -c "./wait_for_it.sh db:5432 -- python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8080"
    environment:
      DB_HOST: db_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
