# Generated by Django 4.2.14 on 2024-07-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_machine', '0001_initial'),
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='locker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post_machine.locker'),
        ),
    ]
